"""Where the gateway config is, asked once.

Five modules resolved this independently -- coverage, discover, rank, and
screen twice -- with the same expression copied five times:

    Path(os.environ.get("GATEWAY_CONFIG", <repo> / "gateway" / "config.yaml"))

That is the "one question, two answers" class, and the fifth copy was added
while fixing a different instance of it. The copies agree today; nothing made
them, and a sixth would agree only by the author remembering.
"""
from __future__ import annotations

import os
from pathlib import Path

ENV_VAR = "GATEWAY_CONFIG"

#: The repo root, two parents up from this file.
REPO = Path(__file__).resolve().parent.parent

DEFAULT = REPO / "gateway" / "config.yaml"

#: LiteLLM prefixes a provider onto the upstream model id. Stripping is how an
#: alias resolves to the repo id mlx_lm.server can hot-swap to, so an
#: UNRECOGNISED prefix silently yields a model name nothing can serve. The
#: tracked configs are asserted against this list, so adding a provider to one
#: without adding it here fails rather than producing a wrong id.
PROVIDER_PREFIXES = ("openai/", "hosted_vllm/", "ollama/", "anthropic/")


def config_path(config=None) -> Path:
    """The gateway config this machine uses."""
    return Path(config or os.environ.get(ENV_VAR) or DEFAULT)


def load(config=None) -> dict:
    """The config's parsed contents, or {} when it cannot be read.

    Fails OPEN by design: a missing or malformed config means "this machine
    serves nothing through a gateway", which is true of a fresh clone, and
    raising here would take down every tier that asks what is served.
    """
    try:
        import yaml
    except ImportError:      # pragma: no cover - yaml is a hard dependency
        return {}
    try:
        return yaml.safe_load(config_path(config).read_text(
            encoding="utf-8")) or {}
    except (OSError, ValueError):
        return {}


def strip_provider(model: str) -> str:
    """The upstream id without LiteLLM's provider prefix."""
    got = (model or "").strip()
    for prefix in PROVIDER_PREFIXES:
        if got.startswith(prefix):
            return got[len(prefix):]
    return got


#: Text lanes the served config names by lane, so a LAN client can ask for `sohot-code`. #297.
TEXT_LANES = ("code", "web", "svg", "extract", "decide", "agent")
LANE_ALIAS = "sohot-{}"


def refresh_gateway() -> None:
    """Re-point the lane aliases to a new adoption once no request is in flight. #297, #483."""
    from harness import gateway_switch
    gateway_switch.spawn()


def served_path(config=None) -> Path:
    """Where the generated config goes: beside its base, so LiteLLM still finds schema_guard."""
    base = config_path(config)
    return base.with_name(f"{base.stem}.served{base.suffix}")


def served(config=None, defaults=None) -> dict:
    """The base config plus a sohot-<lane> alias per text lane's adopted model, and an
    alias by name for an adopted model the base config does not list. #297."""
    from harness import serving
    from harness.completion import DEFAULT_GATEWAY
    data = load(config)
    entries = list(data.get("model_list") or [])
    by_name = {str(e.get("model_name", "")).strip().lower(): e for e in entries}
    if defaults is None:
        from harness import adopt
        defaults = adopt.lane_defaults()
    added = []
    for lane in TEXT_LANES:
        try:
            where = serving.route(defaults.get(lane) or "", config=config)
        except ValueError:
            continue
        known = by_name.get(where.model.lower())
        if where.base == DEFAULT_GATEWAY:
            if known is None:
                continue
            params = dict(known.get("litellm_params") or {})
        else:
            params = {"model": f"openai/{where.model}",
                      "api_base": f"{where.base}/v1", "api_key": "not-needed"}
            if known is None:
                by_name[where.model.lower()] = {"model_name": where.model,
                                                "litellm_params": params}
                added.append(by_name[where.model.lower()])
        added.append({"model_name": LANE_ALIAS.format(lane), "litellm_params": params})
    return {**data, "model_list": entries + added}


def write_served(config=None, defaults=None) -> Path:
    """Write served() beside the base config and return its path."""
    import yaml
    out = served_path(config)
    name = config_path(config).name
    out.write_text(f"# GENERATED by `python -m harness.gateway` from {name} and the "
                   f"adoptions table at serve time. Edit {name}, not this.\n"
                   + yaml.safe_dump(served(config, defaults), sort_keys=False),
                   encoding="utf-8")
    return out


if __name__ == "__main__":
    import sys
    print(write_served(sys.argv[1] if len(sys.argv) > 1 else None))
